"""fix bug2

Revision ID: 3730addb028f
Revises: 38637f267ef9
Create Date: 2023-11-19 15:54:43.267359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3730addb028f'
down_revision: Union[str, None] = '38637f267ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_cookie', ['cookie'])
    op.create_unique_constraint(None, 'user_ip', ['ip'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_ip', type_='unique')
    op.drop_constraint(None, 'user_cookie', type_='unique')
    # ### end Alembic commands ###
