"""vote

Revision ID: d4f7d5b54eb4
Revises: 52e60373c4b9
Create Date: 2023-11-19 14:27:29.820171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f7d5b54eb4'
down_revision: Union[str, None] = '52e60373c4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_cookie', sa.Column('vote', sa.Boolean(), nullable=True))
    op.add_column('vote_cookie_ip', sa.Column('vote', sa.Boolean(), nullable=True))
    op.add_column('vote_ip', sa.Column('vote', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_ip', 'vote')
    op.drop_column('vote_cookie_ip', 'vote')
    op.drop_column('vote_cookie', 'vote')
    # ### end Alembic commands ###
