"""vote2

Revision ID: f5044483020b
Revises: d4f7d5b54eb4
Create Date: 2023-11-19 14:31:40.978247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5044483020b'
down_revision: Union[str, None] = 'd4f7d5b54eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_cookie', sa.Column('user_cookie_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'vote_cookie', ['user_cookie_id'])
    op.create_foreign_key(None, 'vote_cookie', 'user_cookie', ['user_cookie_id'], ['id'])
    op.add_column('vote_cookie_ip', sa.Column('user_ip_id', sa.Integer(), nullable=True))
    op.add_column('vote_cookie_ip', sa.Column('user_cookie_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'vote_cookie_ip', ['user_ip_id'])
    op.create_unique_constraint(None, 'vote_cookie_ip', ['user_cookie_id'])
    op.create_foreign_key(None, 'vote_cookie_ip', 'user_ip', ['user_ip_id'], ['id'])
    op.create_foreign_key(None, 'vote_cookie_ip', 'user_cookie', ['user_cookie_id'], ['id'])
    op.add_column('vote_ip', sa.Column('user_ip_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'vote_ip', ['user_ip_id'])
    op.create_foreign_key(None, 'vote_ip', 'user_ip', ['user_ip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote_ip', type_='foreignkey')
    op.drop_constraint(None, 'vote_ip', type_='unique')
    op.drop_column('vote_ip', 'user_ip_id')
    op.drop_constraint(None, 'vote_cookie_ip', type_='foreignkey')
    op.drop_constraint(None, 'vote_cookie_ip', type_='foreignkey')
    op.drop_constraint(None, 'vote_cookie_ip', type_='unique')
    op.drop_constraint(None, 'vote_cookie_ip', type_='unique')
    op.drop_column('vote_cookie_ip', 'user_cookie_id')
    op.drop_column('vote_cookie_ip', 'user_ip_id')
    op.drop_constraint(None, 'vote_cookie', type_='foreignkey')
    op.drop_constraint(None, 'vote_cookie', type_='unique')
    op.drop_column('vote_cookie', 'user_cookie_id')
    # ### end Alembic commands ###
